services:
  dev:
    image: kevinnls/node_non-root
    user: node
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    expose:
      - '3000'
    entrypoint: ['npm']
    command: 'run dev -- --host'
    env_file:
      - .env.dev

volumes:
  node_modules:
